services:
  app_db:
    ports:
        - 5432:5432
    container_name: app_db
    image: postgres:16.4
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    restart: always

  app_client:
    build: ./client
    container_name: app_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client-app
      - /client-app/node_modules
    stdin_open: true
    tty: true
    restart: always

  app_server:
    build: ./server
    container_name: app_server
    ports:
      - 8080:8080
    environment:
      - SPRING_DB_URL=jdbc:postgresql://app_db:5432/${DB_NAME}
      - SPRING_DB_USERNAME=${DB_USERNAME}
      - SPRING_DB_PASSWORD=${DB_PASSWORD}
      - SPRING_GOOGLE_KEY=${GOOGLE_KEY}
      - SPRING_TASTEDIVE_KEY=${TASTEDIVE_KEY}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_SECURITY_JWT_EXPIRATION_TIME=${SECURITY_JWT_EXPIRATION_TIME}


volumes:
  db-data:
