package com.example.booktracker.user_book.repository;

import com.example.booktracker.user.model.User;
import com.example.booktracker.user_book.ReadingStatus;
import com.example.booktracker.user_book.model.UserBook;
import jakarta.transaction.Transactional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface UserBookRepository extends JpaRepository<UserBook, Long> {
    // CREATE METHODS
    @Modifying
    @Transactional
    @Query(value = """
           INSERT INTO user_book (user_id, book_id, status)
           VALUES (:userId, :bookId, :status)
           ON CONFLICT (user_id, book_id) DO NOTHING
    """, nativeQuery = true)
    void insertIgnoreConflict(@Param("userId") Long userId, @Param("bookId") String bookId,
                              @Param("status") String status);


    // READ METHODS

    // automatically generated by JPA
    boolean existsByUserIdAndBookId(Long userId, String bookId);

    Optional<UserBook> findByUserIdAndBookId(Long userId, String bookId);

    @Query(value = "Select * FROM user_book WHERE user_id = :userId AND status = :status", nativeQuery = true)
    List<UserBook> findByUserIdAndStatus(@Param("userId") Long userId,
                                         @Param("status") String status);    // finds all entities matching the given user id and reading status

    // UPDATE METHODS
    @Modifying
    @Transactional
    @Query(value = """
        UPDATE user_book
        SET status = :newStatus
        WHERE user_id = :userId AND book_id = :bookId
    """, nativeQuery = true)
    int updateStatus(@Param("userId") Long userId,
                     @Param("bookId") String bookId,
                     @Param("newStatus") String newStatus);


    // DELETE METHODS

    // automatically generated by JPA
    @Modifying
    @Transactional
    int deleteByUserIdAndBookId(Long userId, String bookId);

}
